apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: { name: aws-load-balancer-controller, namespace: argocd }
spec:
  project: indus
  source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    targetRevision: 1.13.4
    helm:
      valuesObject:
        clusterName: {{ .Values.clusterName }}
        region: {{ .Values.awsRegion }}
        vpcId: {{ .Values.vpcId }}
        replicaCount: 1
        serviceAccount:
          create: true
          name: aws-load-balancer-controller
          annotations: { eks.amazonaws.com/role-arn: {{ .Values.roles.loadBalancer | quote }} }
        enableServiceMutatorWebhook: false
        podDisruptionBudget: { maxUnavailable: 1 }
        securityContext: { runAsNonRoot: true, seccompProfile: { type: RuntimeDefault } }
  destination: { server: "https://kubernetes.default.svc", namespace: kube-system }
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [ServerSideApply=true]
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: { name: secrets-store-csi-driver, namespace: argocd }
spec:
  project: indus
  source:
    repoURL: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
    chart: secrets-store-csi-driver
    targetRevision: 1.5.3
    helm:
      valuesObject:
        syncSecret: { enabled: true }
        enableSecretRotation: true
        rotationPollInterval: 5m
        linux: { metricsAddr: ":8095" }
  destination: { server: "https://kubernetes.default.svc", namespace: kube-system }
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [ServerSideApply=true]
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: { name: secrets-store-csi-provider-aws, namespace: argocd }
spec:
  project: indus
  source:
    repoURL: https://aws.github.io/secrets-store-csi-driver-provider-aws
    chart: secrets-store-csi-driver-provider-aws
    targetRevision: 2.1.1
    helm:
      valuesObject:
        secrets-store-csi-driver:
          install: false
  destination: { server: "https://kubernetes.default.svc", namespace: kube-system }
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [ServerSideApply=true]
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: { name: metrics-server, namespace: argocd }
spec:
  project: indus
  source:
    repoURL: https://kubernetes-sigs.github.io/metrics-server
    chart: metrics-server
    targetRevision: 3.13.0
    helm:
      valuesObject:
        replicas: 1
  destination: { server: "https://kubernetes.default.svc", namespace: kube-system }
  syncPolicy:
    automated: { prune: true, selfHeal: true }
