import { afterEach, describe, expect, test, vi } from "vitest";
import { createGeminiRequestBody, GeminiApiError, GeminiClient } from "@/lib/ai/geminiClient";

afterEach(() => {
	vi.unstubAllGlobals();
});

describe("createGeminiRequestBody", () => {
	test("keeps system instructions out of user conversation content", () => {
		const body = createGeminiRequestBody([
			{ role: "system", parts: [{ text: "Follow the supplied data." }] },
			{ role: "user", parts: [{ text: "Explain this metric." }] },
		]);

		expect(body.systemInstruction).toEqual({ parts: [{ text: "Follow the supplied data." }] });
		expect(body.contents).toEqual([{ role: "user", parts: [{ text: "Explain this metric." }] }]);
	});
});

describe("GeminiClient.parseSseBuffer", () => {
	test("preserves an incomplete event for the next transport chunk", () => {
		const first = GeminiClient.parseSseBuffer(
			'data: {"candidates":[{"content":{"parts":[{"text":"Hel',
		);
		expect(first.texts).toEqual([]);

		const second = GeminiClient.parseSseBuffer(`${first.remainder}lo"}]}}]}\n\n`);
		expect(second.texts).toEqual(["Hello"]);
		expect(second.remainder).toBe("");
	});

	test("parses multiple complete SSE events", () => {
		const event = (text: string) =>
			`data: ${JSON.stringify({ candidates: [{ content: { parts: [{ text }] } }] })}\n\n`;
		const parsed = GeminiClient.parseSseBuffer(`${event("one")}${event("two")}`);

		expect(parsed.texts).toEqual(["one", "two"]);
	});

	test("flushes a final event without a trailing separator", () => {
		const event = `data: ${JSON.stringify({
			candidates: [{ content: { parts: [{ text: "final" }] } }],
		})}`;

		expect(GeminiClient.parseSseBuffer(event, true)).toEqual({
			texts: ["final"],
			remainder: "",
		});
	});

	test("ignores terminal and malformed provider events", () => {
		const parsed = GeminiClient.parseSseBuffer(
			'data: [DONE]\n\ndata: not-json\n\ndata: {"candidates": []}',
			true,
		);
		expect(parsed).toEqual({ texts: [], remainder: "" });
		expect(GeminiClient.parseStreamChunk("not-json")).toBeNull();
	});
});

describe("GeminiClient provider requests", () => {
	test("requests and returns an SSE response body", async () => {
		const body = new ReadableStream<Uint8Array>();
		const fetchMock = vi.fn().mockResolvedValue(new Response(body));
		vi.stubGlobal("fetch", fetchMock);
		const client = new GeminiClient("secret-key");

		expect(
			await client.generateStreamingContent([{ role: "user", parts: [{ text: "Hello" }] }]),
		).toBe(body);
		expect(fetchMock).toHaveBeenCalledWith(
			expect.stringContaining(":streamGenerateContent?alt=sse"),
			expect.objectContaining({
				headers: expect.objectContaining({ "x-goog-api-key": "secret-key" }),
			}),
		);
	});

	test("rejects failed and empty streaming responses", async () => {
		const client = new GeminiClient("secret-key");
		vi.stubGlobal("fetch", vi.fn().mockResolvedValueOnce(new Response(null, { status: 429 })));
		await expect(client.generateStreamingContent([])).rejects.toBeInstanceOf(GeminiApiError);

		vi.stubGlobal("fetch", vi.fn().mockResolvedValueOnce(new Response(null, { status: 200 })));
		await expect(client.generateStreamingContent([])).rejects.toThrow(
			"Gemini returned an empty response body",
		);
	});

	test("returns generated text and rejects invalid responses", async () => {
		const client = new GeminiClient("secret-key");
		const fetchMock = vi
			.fn()
			.mockResolvedValueOnce(
				Response.json({ candidates: [{ content: { parts: [{ text: "Answer" }] } }] }),
			)
			.mockResolvedValueOnce(Response.json({ candidates: [] }))
			.mockResolvedValueOnce(new Response(null, { status: 503 }));
		vi.stubGlobal("fetch", fetchMock);

		await expect(client.generateContent([])).resolves.toBe("Answer");
		await expect(client.generateContent([])).rejects.toThrow("No content generated by Gemini");
		await expect(client.generateContent([])).rejects.toMatchObject({ status: 503 });
	});
});
