import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Link, useParams } from '@tanstack/react-router'
import { ArrowUpRight, Search as SearchIcon, Sparkles } from 'lucide-react'
import { useState } from 'react'
import { z } from 'zod'
import { chatResponseSchema, favoritePageSchema, favoriteRequest, favoriteSchema, fundamentalsSchema, instrumentPageSchema, marketSummarySchema, portfolioPageSchema, portfolioRequest, portfolioSchema, reportPageSchema, reportRequest, reportSchema, userSchema, userUpdateRequest, type ReportPage } from './lib/api'
import { useAppContext } from './app-context'
import { EmptyState, ErrorState, LoadingState, PageHeader } from './components/States'
import { LivePriceCard } from './components/LivePrice'
import { PriceHistoryCard } from './components/PriceHistory'

export function DashboardPage() {
  const { api } = useAppContext(); const summary = useQuery({ queryKey: ['market-summary'], queryFn: ({ signal }) => api.get('/v1/market/summary', marketSummarySchema, signal), retry: 1 })
  return <div className="mx-auto w-full max-w-[1500px] space-y-8"><section className="relative overflow-hidden rounded-[1.6rem] border border-border/70 bg-card px-5 py-7 shadow-sm sm:px-8 sm:py-9"><div className="pointer-events-none absolute inset-y-0 right-0 hidden w-2/5 bg-[radial-gradient(circle_at_center,color-mix(in_oklab,var(--primary)_13%,transparent),transparent_68%)] md:block"/><div className="relative flex flex-col justify-between gap-7 md:flex-row md:items-end"><div><p className="eyebrow">Dashboard</p><h1 className="font-display mt-3 text-4xl font-medium leading-none tracking-[-.035em] sm:text-5xl">Company research</h1><p className="muted mt-4 max-w-xl text-sm leading-6">Search for a company or continue with one of your favorites.</p></div><div className="flex gap-2"><Link to="/search" className="ui-button rounded-full">Search companies</Link><Link to="/company/$symbol" params={{symbol:'AAPL'}} className="ui-button ui-button-outline rounded-full">Open example</Link></div></div></section>{summary.isPending ? <LoadingState /> : summary.isError ? <ErrorState retry={() => summary.refetch()} /> : <div className="grid gap-4 lg:grid-cols-3">{summary.data.indices.map(item => <article className="card" key={item.symbol}><p className="eyebrow">{item.symbol}</p><p className="mt-3 text-2xl font-semibold financial-number">{money(item.price)}</p><Change value={item.changePercent} /></article>)}<section className="card lg:col-span-3"><h2 className="font-display text-2xl">Your watchlist</h2>{summary.data.watchlist.length === 0 ? <EmptyState title="No instruments yet" detail="Discover a company to build your watchlist." /> : <div className="mt-4 divide-y divide-border">{summary.data.watchlist.map(item => <Link key={item.symbol} to="/company/$symbol" params={{ symbol: item.symbol }} className="flex items-center justify-between py-3"><span><b>{item.symbol}</b><span className="muted ml-3 text-sm">{item.name}</span></span><span>{money(item.price)} <Change value={item.changePercent} /></span></Link>)}</div>}</section></div>}</div>
}

export function SearchPage() {
  const { api } = useAppContext(); const [term, setTerm] = useState(''); const [query, setQuery] = useState('')
  const results = useQuery({ queryKey: ['instrument-search', query], queryFn: ({ signal }) => api.get(`/v1/instruments/search?q=${encodeURIComponent(query)}&page_size=20`, instrumentPageSchema, signal), enabled: query.length > 0, retry: 1 })
  return <><PageHeader eyebrow="Discovery" title="Search markets">Find stocks and digital assets by ticker or company name.</PageHeader><form role="search" onSubmit={event => { event.preventDefault(); setQuery(term.trim()) }} className="card flex gap-3"><label className="sr-only" htmlFor="market-search">Search instruments</label><SearchIcon className="muted mt-2" /><input id="market-search" value={term} onChange={event => setTerm(event.target.value)} placeholder="Try AAPL or Bitcoin" className="w-full bg-transparent px-2 py-2" /><button className="rounded-lg bg-primary px-4 font-semibold text-primary-foreground">Search</button></form><div className="mt-4">{!query ? <EmptyState title="Start with a symbol" detail="Submit a ticker or company name to search the market catalog." /> : results.isPending ? <LoadingState label="Searching markets" /> : results.isError ? <ErrorState retry={() => results.refetch()} /> : results.data.items.length === 0 ? <EmptyState title="No matches" detail="Try a ticker symbol or a less specific company name." /> : <div className="grid gap-3">{results.data.items.map(item => <Link key={item.symbol} to="/company/$symbol" params={{ symbol: item.symbol }} className="card flex items-center justify-between"><span><b>{item.symbol}</b><span className="muted ml-3">{item.name} · {item.exchange ?? item.instrument_type}</span></span><ArrowUpRight /></Link>)}</div>}</div></>
}

export function CompanyPage() {
  const { api } = useAppContext(); const { symbol } = useParams({ from: '/_protected/company/$symbol' }); const normalized = symbol.toUpperCase()
  const fundamentals = useQuery({ queryKey: ['fundamentals', normalized], queryFn: ({ signal }) => api.get(`/v1/fundamentals/${encodeURIComponent(normalized)}`, fundamentalsSchema, signal), retry: 1 })
  const brief = useMutation({ mutationFn: () => api.mutate('/v1/chat', 'POST', { symbol: normalized, messages: [{ role: 'user', content: 'Write a concise research brief using the supplied fundamentals. Cover valuation, profitability, cash flow, balance-sheet strength, and the most important risk. Use plain language and cite the evidence source.' }] }, chatResponseSchema, crypto.randomUUID()) })
  return <><PageHeader eyebrow="Company research" title={normalized}>Fundamentals, valuation, market evidence, and model-assisted explanations.</PageHeader>{fundamentals.isPending ? <LoadingState label="Loading fundamentals" /> : fundamentals.isError ? <ErrorState retry={() => fundamentals.refetch()} /> : <div className="space-y-4"><LivePriceCard symbol={normalized} fallbackPrice={numericMetric(fundamentals.data.metrics.regularMarketPrice)} /><PriceHistoryCard symbol={normalized} /><section className="card"><h2 className="font-semibold">Fundamentals</h2>{Object.keys(fundamentals.data.metrics).length === 0 ? <EmptyState title="No metrics available" detail="The provider has not published fundamentals for this instrument." /> : <dl className="mt-4 grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4">{orderedMetrics(fundamentals.data.metrics).map(([label, value]) => <div key={label}><dt className="muted text-xs uppercase tracking-wide">{metricLabel(label)}</dt><dd className="mt-1 font-semibold">{metricValue(label, value)}</dd></div>)}</dl>}<p className="muted mt-5 text-xs">Source: {fundamentals.data.source} · As of {new Date(fundamentals.data.as_of).toLocaleDateString()}</p></section><section className="card"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="flex items-center gap-2 font-semibold"><Sparkles className="text-primary" size={18} />Research brief</h2><button type="button" className="ui-button rounded-full" disabled={brief.isPending} onClick={() => brief.mutate()}>{brief.isPending ? 'Generating…' : brief.data ? 'Regenerate' : 'Generate brief'}</button></div><p className="mt-4 whitespace-pre-wrap text-sm leading-7">{brief.data?.message.content ?? buildResearchBrief(normalized, fundamentals.data.metrics)}</p>{brief.isError && <p className="mt-3 text-sm text-rose-300" role="alert">The Gemini expansion could not be generated. The financial summary above is still based on the loaded provider data.</p>}<p className="muted mt-4 text-xs">Sources: {brief.data ? brief.data.sources.map(source => source.label).join(', ') : `${fundamentals.data.source} fundamentals`}</p></section></div>}</>
}

export function CryptoPage() {
  const { api } = useAppContext(); const [term, setTerm] = useState(''); const [query, setQuery] = useState('crypto')
  const assets = useQuery({ queryKey: ['crypto-search', query], queryFn: ({ signal }) => api.get(`/v1/instruments/search?q=${encodeURIComponent(query)}&page_size=20`, instrumentPageSchema, signal), retry: 1 })
  const cryptoAssets = assets.data?.items.filter(item => item.instrument_type === 'crypto') ?? []
  return <><PageHeader eyebrow="Digital assets" title="Crypto markets">Discover digital assets with an authenticated live market signal and research snapshot.</PageHeader>{cryptoAssets[0] && <div className="mb-4"><LivePriceCard symbol={cryptoAssets[0].symbol} /></div>}<form role="search" onSubmit={event => { event.preventDefault(); setQuery(term.trim() || 'crypto') }} className="card flex gap-3"><label className="sr-only" htmlFor="crypto-search">Search digital assets</label><SearchIcon className="muted mt-2" /><input id="crypto-search" value={term} onChange={event => setTerm(event.target.value)} placeholder="Try Bitcoin or BTC/USD" className="w-full bg-transparent px-2 py-2" /><button className="rounded-lg bg-primary px-4 font-semibold text-primary-foreground">Search</button></form><section className="mt-4">{assets.isPending ? <LoadingState label="Loading digital assets" /> : assets.isError ? <ErrorState retry={() => assets.refetch()} /> : cryptoAssets.length === 0 ? <EmptyState title="No digital assets found" detail="Try a common asset name or slash-delimited symbol." /> : <div className="grid gap-3 md:grid-cols-2">{cryptoAssets.map(item => <Link key={item.symbol} to="/company/$symbol" params={{ symbol: item.symbol }} className="card flex items-center justify-between"><span><b>{item.symbol}</b><span className="muted ml-3">{item.name}</span></span><ArrowUpRight /></Link>)}</div>}</section></>
}

export function FavoritesPage() {
  const { api } = useAppContext(); const cache = useQueryClient(); const [symbol, setSymbol] = useState('')
  const favorites = useQuery({ queryKey: ['favorites'], queryFn: ({ signal }) => api.get('/v1/favorites?page_size=100', favoritePageSchema, signal), retry: 1 })
  const add = useMutation({ mutationFn: (value: string) => api.mutate('/v1/favorites', 'POST', favoriteRequest({ symbol: value.toUpperCase(), instrumentType: 'equity' }), favoriteSchema, crypto.randomUUID()), onSuccess: () => { setSymbol(''); void cache.invalidateQueries({ queryKey: ['favorites'] }) } })
  const remove = useMutation({ mutationFn: (id: string) => api.mutate(`/v1/favorites/${id}`, 'DELETE', undefined, zUndefined, crypto.randomUUID()), onSuccess: () => void cache.invalidateQueries({ queryKey: ['favorites'] }) })
  return <><PageHeader eyebrow="Research library" title="Favorites">Your saved companies and assets, synchronized to your account.</PageHeader><form onSubmit={event => { event.preventDefault(); if (symbol.trim()) add.mutate(symbol.trim()) }} className="card mb-4 flex gap-3"><label className="sr-only" htmlFor="favorite-symbol">Symbol</label><input id="favorite-symbol" value={symbol} onChange={event => setSymbol(event.target.value)} placeholder="Add a symbol" maxLength={20} className="w-full bg-transparent px-2 py-2" /><button disabled={add.isPending} className="rounded-lg bg-primary px-4 font-semibold text-primary-foreground">Add</button></form>{(add.isError || remove.isError) && <p role="alert" className="mb-4 text-rose-300">The favorite could not be updated. Try again.</p>}{favorites.isPending ? <LoadingState /> : favorites.isError ? <ErrorState retry={() => favorites.refetch()} /> : favorites.data.items.length === 0 ? <EmptyState title="No favorites yet" detail="Add a symbol to create your research shortlist." /> : <div className="grid gap-3">{favorites.data.items.map(item => <article className="card flex items-center justify-between" key={item.id}><Link to="/company/$symbol" params={{ symbol: item.symbol }}><b>{item.symbol}</b><span className="muted ml-3 text-sm">{item.instrument_type}</span></Link><button onClick={() => remove.mutate(item.id)} className="text-sm text-rose-300">Remove</button></article>)}</div>}</>
}

export function PortfoliosPage() {
  const { api } = useAppContext(); const cache = useQueryClient(); const [name, setName] = useState('')
  const portfolios = useQuery({ queryKey: ['portfolios'], queryFn: ({ signal }) => api.get('/v1/portfolios?page_size=100', portfolioPageSchema, signal), retry: 1 })
  const create = useMutation({ mutationFn: (value: string) => api.mutate('/v1/portfolios', 'POST', portfolioRequest({ name: value, baseCurrency: 'USD' }), portfolioSchema, crypto.randomUUID()), onSuccess: () => { setName(''); void cache.invalidateQueries({ queryKey: ['portfolios'] }) } })
  return <><PageHeader eyebrow="Allocation" title="Portfolios">Create portfolios to understand concentration, exposure, and performance.</PageHeader><form onSubmit={event => { event.preventDefault(); if (name.trim()) create.mutate(name.trim()) }} className="card mb-4 flex gap-3"><label className="sr-only" htmlFor="portfolio-name">Portfolio name</label><input id="portfolio-name" value={name} onChange={event => setName(event.target.value)} placeholder="New portfolio name" maxLength={100} className="w-full bg-transparent px-2 py-2" /><button disabled={create.isPending} className="rounded-lg bg-primary px-4 font-semibold text-primary-foreground">Create</button></form>{create.isError && <p role="alert" className="mb-4 text-rose-300">The portfolio could not be created.</p>}{portfolios.isPending ? <LoadingState /> : portfolios.isError ? <ErrorState retry={() => portfolios.refetch()} /> : portfolios.data.items.length === 0 ? <EmptyState title="No portfolios yet" detail="Create a portfolio to organize positions and research." /> : <div className="grid gap-3 md:grid-cols-2">{portfolios.data.items.map(item => <article className="card" key={item.id}><h2 className="font-semibold">{item.name}</h2><p className="muted mt-2 text-sm">Base currency · {item.base_currency}</p></article>)}</div>}</>
}

export function ReportsPage() {
  const { api } = useAppContext(); const cache = useQueryClient(); const [symbol, setSymbol] = useState('')
  const reports = useQuery({ queryKey: ['reports'], queryFn: ({ signal }) => api.get('/v1/reports?page_size=100', reportPageSchema, signal), retry: 1, refetchInterval: query => query.state.data?.items.some(item => item.status === 'queued' || item.status === 'generating') ? 2_000 : false })
  const create = useMutation({ mutationFn: (value: string) => api.mutate('/v1/reports', 'POST', reportRequest({ symbol: value.toUpperCase() }), reportSchema, crypto.randomUUID()), onSuccess: () => { setSymbol(''); void cache.invalidateQueries({ queryKey: ['reports'] }) } })
  const cancel = useMutation({ mutationFn: (id: string) => api.mutate(`/v1/reports/${encodeURIComponent(id)}/cancel`, 'POST', undefined, reportSchema, crypto.randomUUID()), onSuccess: updated => cache.setQueryData<ReportPage>(['reports'], current => current ? { ...current, items: current.items.map(item => item.id === updated.id ? updated : item) } : current) })
  return <><PageHeader eyebrow="Long-form research" title="Reports">Generate and revisit evidence-backed company research.</PageHeader><form onSubmit={event => { event.preventDefault(); if (symbol.trim()) create.mutate(symbol.trim()) }} className="card mb-4 flex gap-3"><label className="sr-only" htmlFor="report-symbol">Company symbol</label><input id="report-symbol" value={symbol} onChange={event => setSymbol(event.target.value)} placeholder="Company symbol" maxLength={20} className="w-full bg-transparent px-2 py-2" /><button disabled={create.isPending} className="rounded-lg bg-primary px-4 font-semibold text-primary-foreground">Generate</button></form>{create.isError && <p role="alert" className="mb-4 text-rose-300">The report request could not be queued.</p>}{cancel.isError && <p role="alert" className="mb-4 text-rose-300">The report cancellation could not be requested.</p>}{reports.isPending ? <LoadingState /> : reports.isError ? <ErrorState retry={() => reports.refetch()} /> : reports.data.items.length === 0 ? <EmptyState title="No reports yet" detail="Generate a report to begin your research archive." /> : <div className="grid gap-3">{reports.data.items.map(item => <article className="card flex items-center justify-between gap-4" key={item.id}><span><b>{item.title}</b><span className="muted ml-3 text-sm">{item.symbol}</span></span><span className="flex items-center gap-3"><span className="rounded-full bg-muted px-3 py-1 text-xs capitalize">{item.status}</span>{(item.status === 'queued' || item.status === 'generating') && <button type="button" disabled={cancel.isPending && cancel.variables === item.id} onClick={() => cancel.mutate(item.id)} className="text-sm text-rose-300 disabled:opacity-60">{cancel.isPending && cancel.variables === item.id ? 'Cancelling…' : 'Cancel'}</button>}</span></article>)}</div>}</>
}

export function SettingsPage() {
  const { api } = useAppContext(); const cache = useQueryClient(); const [draft, setDraft] = useState('')
  const user = useQuery({ queryKey: ['current-user'], queryFn: ({ signal }) => api.get('/v1/me', userSchema, signal), retry: 1 })
  const save = useMutation({ mutationFn: (displayName: string) => api.mutate('/v1/me', 'PATCH', userUpdateRequest({ displayName }), userSchema, crypto.randomUUID()), onSuccess: data => { cache.setQueryData(['current-user'], data); setDraft('') } })
  return <><PageHeader eyebrow="Account" title="Settings">Manage your profile and account preferences.</PageHeader>{user.isPending ? <LoadingState /> : user.isError ? <ErrorState retry={() => user.refetch()} /> : <form onSubmit={event => { event.preventDefault(); save.mutate(draft.trim() || user.data.display_name) }} className="card max-w-xl space-y-4"><label className="block text-sm">Email<input disabled value={user.data.email} className="mt-2 w-full rounded-lg border border-border bg-card px-3 py-2.5 disabled:opacity-60" /></label><label className="block text-sm">Display name<input value={draft || user.data.display_name} onChange={event => setDraft(event.target.value)} maxLength={100} className="mt-2 w-full rounded-lg border border-border bg-card px-3 py-2.5" /></label>{save.isError && <p role="alert" className="text-rose-300">Your settings could not be saved.</p>}<button disabled={save.isPending} className="rounded-lg bg-primary px-4 py-2 font-semibold text-primary-foreground">Save changes</button></form>}</>
}

function Change({ value }: { value: number }) { return <span className={`ml-2 text-sm ${value >= 0 ? 'text-emerald-400' : 'text-rose-400'}`}>{value >= 0 ? '+' : ''}{value.toFixed(2)}%</span> }
function money(value: number) { return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(value) }
const metricLabels: Record<string, string> = {
  regularMarketPrice: 'Market Price', regularMarketChangePercent: 'Daily Change', regularMarketDayHigh: 'Day High', regularMarketDayLow: 'Day Low',
  regularMarketVolume: 'Volume', fiftyTwoWeekHigh: '52-Week High', fiftyTwoWeekLow: '52-Week Low', shortName: 'Company', market_cap: 'Market Cap',
  trailing_pe_ratio: 'P/E Ratio', revenue_ttm: 'Revenue (TTM)', gross_profit_ttm: 'Gross Profit (TTM)', operating_income_ttm: 'Operating Income (TTM)',
  net_income_ttm: 'Net Income (TTM)', ebitda_ttm: 'EBITDA (TTM)', diluted_eps_ttm: 'Diluted EPS (TTM)', operating_cash_flow_ttm: 'Operating Cash Flow (TTM)',
  free_cash_flow_ttm: 'Free Cash Flow (TTM)', total_assets: 'Total Assets', total_debt: 'Total Debt', stockholders_equity: 'Stockholders’ Equity',
  cash_and_equivalents: 'Cash & Equivalents', current_assets: 'Current Assets', current_liabilities: 'Current Liabilities', gross_margin: 'Gross Margin',
  operating_margin: 'Operating Margin', net_margin: 'Net Margin', current_ratio: 'Current Ratio', debt_to_equity: 'Debt to Equity',
}
const priceMetrics = new Set(['regularMarketPrice', 'regularMarketDayHigh', 'regularMarketDayLow', 'fiftyTwoWeekHigh', 'fiftyTwoWeekLow', 'diluted_eps_ttm'])
const compactCurrencyMetrics = new Set(['market_cap', 'revenue_ttm', 'gross_profit_ttm', 'operating_income_ttm', 'net_income_ttm', 'ebitda_ttm', 'operating_cash_flow_ttm', 'free_cash_flow_ttm', 'total_assets', 'total_debt', 'stockholders_equity', 'cash_and_equivalents', 'current_assets', 'current_liabilities'])
const ratioMetrics = new Set(['trailing_pe_ratio', 'current_ratio', 'debt_to_equity'])
const marginMetrics = new Set(['gross_margin', 'operating_margin', 'net_margin'])

function orderedMetrics(metrics: Record<string, number | string | null>) {
  const order = Object.keys(metricLabels)
  return Object.entries(metrics).sort(([left], [right]) => {
    const leftIndex = order.indexOf(left); const rightIndex = order.indexOf(right)
    return (leftIndex < 0 ? order.length : leftIndex) - (rightIndex < 0 ? order.length : rightIndex)
  })
}
function numericMetric(value: number | string | null | undefined) { return typeof value === 'number' ? value : undefined }
function metricLabel(key: string) {
  if (metricLabels[key]) return metricLabels[key]
  return key.replaceAll('_', ' ').replace(/([a-z0-9])([A-Z])/g, '$1 $2').replace(/\b\w/g, character => character.toUpperCase())
}
function metricValue(key: string, value: number | string | null) {
  if (value === null) return '—'
  if (typeof value === 'string') return value
  if (priceMetrics.has(key)) return money(value)
  if (compactCurrencyMetrics.has(key)) return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', notation: 'compact', maximumFractionDigits: 2 }).format(value)
  if (key === 'regularMarketVolume') return new Intl.NumberFormat('en-US', { notation: 'compact', maximumFractionDigits: 1 }).format(value)
  if (key === 'regularMarketChangePercent') return `${value.toFixed(2)}%`
  if (marginMetrics.has(key)) return `${(value * 100).toFixed(1)}%`
  if (ratioMetrics.has(key)) return `${value.toFixed(2)}×`
  return new Intl.NumberFormat('en-US', { maximumFractionDigits: 2 }).format(value)
}
function buildResearchBrief(symbol: string, metrics: Record<string, number | string | null>) {
  const company = typeof metrics.shortName === 'string' ? metrics.shortName : symbol
  const sentences: string[] = []
  const price = numericMetric(metrics.regularMarketPrice); const marketCap = numericMetric(metrics.market_cap); const pe = numericMetric(metrics.trailing_pe_ratio)
  if (price !== undefined) sentences.push(`${company} is trading at ${money(price)}${marketCap !== undefined ? ` with a market capitalization of ${metricValue('market_cap', marketCap)}` : ''}${pe !== undefined ? ` and a trailing P/E ratio of ${metricValue('trailing_pe_ratio', pe)}` : ''}.`)
  const revenue = numericMetric(metrics.revenue_ttm); const income = numericMetric(metrics.net_income_ttm); const margin = numericMetric(metrics.net_margin); const cashFlow = numericMetric(metrics.free_cash_flow_ttm)
  if (revenue !== undefined) sentences.push(`Over the trailing twelve months, revenue was ${metricValue('revenue_ttm', revenue)}${income !== undefined ? ` and net income was ${metricValue('net_income_ttm', income)}` : ''}${margin !== undefined ? `, producing a ${metricValue('net_margin', margin)} net margin` : ''}${cashFlow !== undefined ? `; free cash flow was ${metricValue('free_cash_flow_ttm', cashFlow)}` : ''}.`)
  const cash = numericMetric(metrics.cash_and_equivalents); const debt = numericMetric(metrics.total_debt); const currentRatio = numericMetric(metrics.current_ratio)
  if (cash !== undefined || debt !== undefined || currentRatio !== undefined) sentences.push(`The latest balance sheet shows${cash !== undefined ? ` ${metricValue('cash_and_equivalents', cash)} in cash and equivalents` : ''}${debt !== undefined ? `, ${metricValue('total_debt', debt)} in total debt` : ''}${currentRatio !== undefined ? `, and a current ratio of ${metricValue('current_ratio', currentRatio)}` : ''}.`)
  return sentences.join(' ') || `Provider fundamentals are available for ${company}, but there is not enough normalized evidence to produce a financial summary.`
}
const zUndefined = z.undefined()
