import { useQuery } from '@tanstack/react-query'
import { Link, useNavigate, useParams } from '@tanstack/react-router'
import { ArrowUpRight, Search as SearchIcon, ShieldCheck, Sparkles } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { marketSummarySchema } from './lib/api'
import { useAppContext } from './app-context'
import { EmptyState, ErrorState, LoadingState, PageHeader } from './components/States'

export function AuthPage() {
  const { auth } = useAppContext(); const navigate = useNavigate(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { await auth.signIn(email, password); await navigate({ to: '/dashboard' }) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Sign in failed.') } finally { setBusy(false) } }
  return <main className="grid min-h-screen place-items-center p-5"><section className="w-full max-w-md rounded-2xl border border-slate-800 bg-slate-950/80 p-7 shadow-2xl"><p className="eyebrow">Financial intelligence</p><h1 className="mt-3 text-3xl font-semibold">Welcome to Indus</h1><p className="muted mt-2">Research markets with evidence, context, and clear controls.</p><form onSubmit={submit} className="mt-7 space-y-4">{error && <p role="alert" className="rounded-lg border border-rose-900 bg-rose-950/40 p-3 text-sm text-rose-200">{error}</p>}<label className="block text-sm">Email<input required type="email" autoComplete="email" value={email} onChange={e => setEmail(e.target.value)} className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-900 px-3 py-2.5" /></label><label className="block text-sm">Password<input required type="password" autoComplete="current-password" value={password} onChange={e => setPassword(e.target.value)} className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-900 px-3 py-2.5" /></label><button disabled={busy} className="w-full rounded-lg bg-sky-400 px-4 py-3 font-semibold text-slate-950 disabled:opacity-60">{busy ? 'Signing in…' : 'Sign in securely'}</button></form><p className="muted mt-6 flex items-center gap-2 text-xs"><ShieldCheck size={15} />Credentials are sent only to the configured identity provider.</p></section></main>
}

export function DashboardPage() {
  const { api } = useAppContext(); const summary = useQuery({ queryKey: ['market-summary'], queryFn: ({ signal }) => api.get('/v1/market/summary', marketSummarySchema, signal), retry: 1 })
  return <><PageHeader eyebrow="Market pulse" title="Good morning">Monitor the instruments and research that matter to you.</PageHeader>{summary.isPending ? <LoadingState /> : summary.isError ? <ErrorState retry={() => summary.refetch()} /> : <div className="grid gap-4 lg:grid-cols-3">{summary.data.indices.map(item => <article className="card" key={item.symbol}><p className="muted text-sm">{item.symbol}</p><p className="mt-3 text-2xl font-semibold">{money(item.price)}</p><Change value={item.changePercent} /></article>)}<section className="card lg:col-span-3"><h2 className="font-semibold">Your watchlist</h2>{summary.data.watchlist.length === 0 ? <EmptyState title="No instruments yet" detail="Discover a company to build your watchlist." /> : <div className="mt-4 divide-y divide-slate-800">{summary.data.watchlist.map(item => <Link key={item.symbol} to="/company/$symbol" params={{ symbol: item.symbol }} className="flex items-center justify-between py-3"><span><b>{item.symbol}</b><span className="muted ml-3 text-sm">{item.name}</span></span><span>{money(item.price)} <Change value={item.changePercent} /></span></Link>)}</div>}</section></div>}</>
}

export function SearchPage() { const [term, setTerm] = useState(''); return <><PageHeader eyebrow="Discovery" title="Search markets">Find stocks and digital assets by ticker or company name.</PageHeader><form role="search" onSubmit={e => e.preventDefault()} className="card flex gap-3"><label className="sr-only" htmlFor="market-search">Search instruments</label><SearchIcon className="muted mt-2" /><input id="market-search" value={term} onChange={e => setTerm(e.target.value)} placeholder="Try AAPL or Bitcoin" className="w-full bg-transparent px-2 py-2" /></form><div className="mt-4">{term ? <Link to="/company/$symbol" params={{ symbol: term.toUpperCase() }} className="card flex items-center justify-between"><span><b>{term.toUpperCase()}</b><span className="muted ml-3">View instrument research</span></span><ArrowUpRight /></Link> : <EmptyState title="Start with a symbol" detail="Results will appear as you search." />}</div></> }
export function CompanyPage() { const { symbol } = useParams({ from: '/_protected/company/$symbol' }); return <><PageHeader eyebrow="Company research" title={symbol.toUpperCase()}>Fundamentals, valuation, market evidence, and model-assisted explanations.</PageHeader><div className="grid gap-4 lg:grid-cols-2"><section className="card min-h-64"><h2 className="font-semibold">Price history</h2><p className="muted mt-2 text-sm">Live price streaming activates in Phase 3 through the market stream adapter.</p></section><section className="card"><h2 className="flex items-center gap-2 font-semibold"><Sparkles className="text-sky-300" size={18} />Research brief</h2><p className="muted mt-3">Generated analysis will cite provider evidence and preserve request boundaries.</p></section></div></> }

const pageCopy = {
  crypto: ['Digital assets', 'Crypto markets', 'Track slash-delimited digital asset pairs through the same secure market boundary.'],
  favorites: ['Research library', 'Favorites', 'Your saved companies and assets, synchronized to your account.'],
  portfolios: ['Allocation', 'Portfolios', 'Create portfolios to understand concentration, exposure, and performance.'],
  reports: ['Long-form research', 'Reports', 'Generate and revisit evidence-backed company research.'],
  settings: ['Account', 'Settings', 'Manage your profile, preferences, and security.'],
} as const
export function PlaceholderPage({ kind }: { kind: keyof typeof pageCopy }) { const [eyebrow, title, detail] = pageCopy[kind]; return <><PageHeader eyebrow={eyebrow} title={title}>{detail}</PageHeader><EmptyState title={`${title} is ready for migration`} detail="The Rails contract will populate this view as its endpoint becomes available." /></> }
function Change({ value }: { value: number }) { return <span className={`ml-2 text-sm ${value >= 0 ? 'text-emerald-400' : 'text-rose-400'}`}>{value >= 0 ? '+' : ''}{value.toFixed(2)}%</span> }
function money(value: number) { return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(value) }
