import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Link, useNavigate, useParams } from '@tanstack/react-router'
import { ArrowRight, ArrowUpRight, BrainCircuit, Check, DatabaseZap, LineChart, LockKeyhole, Search as SearchIcon, ShieldCheck, Sparkles } from 'lucide-react'
import { useEffect, useState } from 'react'
import { z } from 'zod'
import { favoritePageSchema, favoriteRequest, favoriteSchema, fundamentalsSchema, instrumentPageSchema, marketSummarySchema, portfolioPageSchema, portfolioRequest, portfolioSchema, reportPageSchema, reportRequest, reportSchema, userSchema, userUpdateRequest, type ReportPage } from './lib/api'
import { useAppContext } from './app-context'
import { EmptyState, ErrorState, LoadingState, PageHeader } from './components/States'
import { LivePriceCard } from './components/LivePrice'

export function AuthPage() {
	const { auth } = useAppContext(); const navigate = useNavigate(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
	const signIn = async () => { setBusy(true); setError(''); try { await auth.signIn(); if (await auth.getUser()) await navigate({ to: '/dashboard', replace: true }) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Sign in failed.'); setBusy(false) } }
	return <main className="auth-page"><a href="/" className="brand auth-brand"><img src="/logo.svg" alt="" /><span>Indus</span></a><section className="auth-panel"><div className="auth-copy"><p className="eyebrow">Your research workspace</p><h1>Welcome back.</h1><p>Track markets, study company fundamentals, and turn live evidence into clearer investment research.</p><ul><li><LineChart />Live stock and crypto signals</li><li><BrainCircuit />AI analysis grounded in current data</li><li><ShieldCheck />Private portfolios and research</li></ul></div><div className="auth-card"><img src="/logo.svg" alt="" className="auth-mark" /><p className="eyebrow">Sign in to Indus</p><h2>Continue your research</h2><p className="muted">Use your Indus account to securely access your workspace.</p>{error && <p role="alert" className="auth-error">{error}</p>}<button type="button" onClick={signIn} disabled={busy} className="primary-button auth-button">{busy ? 'Opening sign in…' : <>Continue to sign in <ArrowRight size={17} /></>}</button><p className="auth-note"><LockKeyhole size={14} />Secure authentication and account recovery</p></div></section></main>
}

export function LandingPage() {
  return <div className="landing" id="top"><header className="landing-nav"><a href="/" className="brand"><img src="/logo.svg" alt="" /><span>Indus</span></a><nav aria-label="Main navigation"><a href="#product">Product</a><a href="#workflow">Workflow</a><a href="#principles">Principles</a></nav><a href="/auth" className="nav-cta">Sign in <ArrowRight size={16} /></a></header><main><section className="hero"><div className="hero-copy"><p className="eyebrow">Research beyond the headline</p><h1>Financial intelligence, <em>in context.</em></h1><p>Live price action, durable company fundamentals, and AI-assisted analysis in one focused workspace.</p><div className="hero-actions"><a href="/auth" className="primary-button">Start researching <ArrowRight size={17} /></a><a href="#product" className="secondary-button">See the product</a></div><div className="trust-row"><span><Check />Live market data</span><span><Check />Evidence-backed analysis</span><span><Check />Private by design</span></div></div><ProductPreview /></section><section className="workflow" id="workflow"><div><p className="eyebrow">One research flow</p><h2>Move from market signal to informed view.</h2></div><div className="steps">{[['01','Search the market','Find stocks and digital assets in seconds.'],['02','Read the evidence','Review live prices, fundamentals, and valuation together.'],['03','Ask better questions','Use AI analysis grounded in the data on screen.']].map(([n,t,c]) => <article key={n}><span>{n}</span><div><h3>{t}</h3><p>{c}</p></div></article>)}</div></section><section className="principles" id="principles"><p className="eyebrow">Built for clarity</p><h2>Know what you are looking at.</h2><div className="principle-grid">{[[DatabaseZap,'Current market context','See live, reconnecting, and historical data states clearly.'],[LineChart,'Research in one view','Connect price action with company fundamentals and valuation.'],[LockKeyhole,'Evidence-aware AI','Get explanations tied to the metrics and market data in view.']].map(([Icon,title,copy]) => { const I = Icon as typeof DatabaseZap; return <article key={title as string}><I /><h3>{title as string}</h3><p>{copy as string}</p></article> })}</div></section></main><footer><a href="/" className="brand"><img src="/logo.svg" alt="" /><span>Indus</span></a><p>Market data, company fundamentals, and AI analysis in one workspace.</p><span>© {new Date().getFullYear()} Indus</span></footer></div>
}

function ProductPreview() { return <div className="product-preview" id="product"><div className="preview-bar"><span><i />Company research</span><small>LIVE</small></div><div className="preview-grid"><section><div className="quote-row"><div><b>AAPL</b><span>Apple Inc.</span></div><div><strong>$213.32</strong><em>+1.28%</em></div></div><div className="chart"><svg viewBox="0 0 560 210" preserveAspectRatio="none" aria-label="Illustrative upward price chart"><defs><linearGradient id="chart-fill" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#adde59" stopOpacity=".28"/><stop offset="1" stopColor="#adde59" stopOpacity="0"/></linearGradient></defs><path className="chart-area" d="M0 170 C55 165 70 185 115 146 S175 150 220 115 S285 142 330 99 S397 110 438 66 S498 70 560 22 V210 H0Z"/><path className="chart-line" d="M0 170 C55 165 70 185 115 146 S175 150 220 115 S285 142 330 99 S397 110 438 66 S498 70 560 22"/></svg></div><div className="metrics"><span>Market cap <b>$3.19T</b></span><span>P/E ratio <b>33.1×</b></span><span>Net margin <b>24.3%</b></span></div></section><aside><div><BrainCircuit size={17}/>Indus analyst</div><h3>“How does this margin compare with the valuation?”</h3><p>A 24.3% net margin and 33.1× P/E connect profitability to the price paid for earnings.</p><small><Check size={13}/>Based on current metrics</small></aside></div></div> }

export function AuthCallbackPage() {
	const { auth } = useAppContext(); const navigate = useNavigate(); const [error, setError] = useState('')
	useEffect(() => { void auth.completeSignIn().then(() => navigate({ to: '/dashboard', replace: true })).catch(cause => setError(cause instanceof Error ? cause.message : 'Sign in could not be completed.')) }, [auth, navigate])
	return <main className="grid min-h-screen place-items-center p-5"><section className="card w-full max-w-md text-center">{error ? <><h1 className="text-2xl font-semibold">Sign in failed</h1><p role="alert" className="mt-3 text-rose-300">{error}</p><a href="/auth" className="mt-5 inline-block text-sky-300">Try again</a></> : <><h1 className="text-2xl font-semibold">Completing sign in</h1><p role="status" className="muted mt-3">Verifying your secure session…</p></>}</section></main>
}

export function DashboardPage() {
  const { api } = useAppContext(); const summary = useQuery({ queryKey: ['market-summary'], queryFn: ({ signal }) => api.get('/v1/market/summary', marketSummarySchema, signal), retry: 1 })
  return <><PageHeader eyebrow="Market pulse" title="Good morning">Monitor the instruments and research that matter to you.</PageHeader>{summary.isPending ? <LoadingState /> : summary.isError ? <ErrorState retry={() => summary.refetch()} /> : <div className="grid gap-4 lg:grid-cols-3">{summary.data.indices.map(item => <article className="card" key={item.symbol}><p className="muted text-sm">{item.symbol}</p><p className="mt-3 text-2xl font-semibold">{money(item.price)}</p><Change value={item.changePercent} /></article>)}<section className="card lg:col-span-3"><h2 className="font-semibold">Your watchlist</h2>{summary.data.watchlist.length === 0 ? <EmptyState title="No instruments yet" detail="Discover a company to build your watchlist." /> : <div className="mt-4 divide-y divide-slate-800">{summary.data.watchlist.map(item => <Link key={item.symbol} to="/company/$symbol" params={{ symbol: item.symbol }} className="flex items-center justify-between py-3"><span><b>{item.symbol}</b><span className="muted ml-3 text-sm">{item.name}</span></span><span>{money(item.price)} <Change value={item.changePercent} /></span></Link>)}</div>}</section></div>}</>
}

export function SearchPage() {
  const { api } = useAppContext(); const [term, setTerm] = useState(''); const [query, setQuery] = useState('')
  const results = useQuery({ queryKey: ['instrument-search', query], queryFn: ({ signal }) => api.get(`/v1/instruments/search?q=${encodeURIComponent(query)}&page_size=20`, instrumentPageSchema, signal), enabled: query.length > 0, retry: 1 })
  return <><PageHeader eyebrow="Discovery" title="Search markets">Find stocks and digital assets by ticker or company name.</PageHeader><form role="search" onSubmit={event => { event.preventDefault(); setQuery(term.trim()) }} className="card flex gap-3"><label className="sr-only" htmlFor="market-search">Search instruments</label><SearchIcon className="muted mt-2" /><input id="market-search" value={term} onChange={event => setTerm(event.target.value)} placeholder="Try AAPL or Bitcoin" className="w-full bg-transparent px-2 py-2" /><button className="rounded-lg bg-sky-400 px-4 font-semibold text-slate-950">Search</button></form><div className="mt-4">{!query ? <EmptyState title="Start with a symbol" detail="Submit a ticker or company name to search the market catalog." /> : results.isPending ? <LoadingState label="Searching markets" /> : results.isError ? <ErrorState retry={() => results.refetch()} /> : results.data.items.length === 0 ? <EmptyState title="No matches" detail="Try a ticker symbol or a less specific company name." /> : <div className="grid gap-3">{results.data.items.map(item => <Link key={item.symbol} to="/company/$symbol" params={{ symbol: item.symbol }} className="card flex items-center justify-between"><span><b>{item.symbol}</b><span className="muted ml-3">{item.name} · {item.exchange ?? item.instrument_type}</span></span><ArrowUpRight /></Link>)}</div>}</div></>
}

export function CompanyPage() {
  const { api } = useAppContext(); const { symbol } = useParams({ from: '/_protected/company/$symbol' }); const normalized = symbol.toUpperCase()
  const fundamentals = useQuery({ queryKey: ['fundamentals', normalized], queryFn: ({ signal }) => api.get(`/v1/fundamentals/${encodeURIComponent(normalized)}`, fundamentalsSchema, signal), retry: 1 })
  return <><PageHeader eyebrow="Company research" title={normalized}>Fundamentals, valuation, market evidence, and model-assisted explanations.</PageHeader>{fundamentals.isPending ? <LoadingState label="Loading fundamentals" /> : fundamentals.isError ? <ErrorState retry={() => fundamentals.refetch()} /> : <div className="grid gap-4 lg:grid-cols-2"><LivePriceCard symbol={normalized} /><section className="card"><h2 className="font-semibold">Fundamentals</h2>{Object.keys(fundamentals.data.metrics).length === 0 ? <EmptyState title="No metrics available" detail="The provider has not published fundamentals for this instrument." /> : <dl className="mt-4 grid grid-cols-2 gap-4">{Object.entries(fundamentals.data.metrics).map(([label, value]) => <div key={label}><dt className="muted text-xs uppercase tracking-wide">{label.replaceAll('_', ' ')}</dt><dd className="mt-1 font-semibold">{value ?? '—'}</dd></div>)}</dl>}<p className="muted mt-5 text-xs">Source: {fundamentals.data.source} · As of {new Date(fundamentals.data.as_of).toLocaleDateString()}</p></section><section className="card lg:col-span-2"><h2 className="flex items-center gap-2 font-semibold"><Sparkles className="text-sky-300" size={18} />Research brief</h2><p className="muted mt-3">Generated analysis will cite provider evidence and preserve request boundaries.</p></section></div>}</>
}

export function CryptoPage() {
  const { api } = useAppContext(); const [term, setTerm] = useState(''); const [query, setQuery] = useState('crypto')
  const assets = useQuery({ queryKey: ['crypto-search', query], queryFn: ({ signal }) => api.get(`/v1/instruments/search?q=${encodeURIComponent(query)}&page_size=20`, instrumentPageSchema, signal), retry: 1 })
  const cryptoAssets = assets.data?.items.filter(item => item.instrument_type === 'crypto') ?? []
  return <><PageHeader eyebrow="Digital assets" title="Crypto markets">Discover digital assets with an authenticated live market signal and research snapshot.</PageHeader>{cryptoAssets[0] && <div className="mb-4"><LivePriceCard symbol={cryptoAssets[0].symbol} /></div>}<form role="search" onSubmit={event => { event.preventDefault(); setQuery(term.trim() || 'crypto') }} className="card flex gap-3"><label className="sr-only" htmlFor="crypto-search">Search digital assets</label><SearchIcon className="muted mt-2" /><input id="crypto-search" value={term} onChange={event => setTerm(event.target.value)} placeholder="Try Bitcoin or BTC/USD" className="w-full bg-transparent px-2 py-2" /><button className="rounded-lg bg-sky-400 px-4 font-semibold text-slate-950">Search</button></form><section className="mt-4">{assets.isPending ? <LoadingState label="Loading digital assets" /> : assets.isError ? <ErrorState retry={() => assets.refetch()} /> : cryptoAssets.length === 0 ? <EmptyState title="No digital assets found" detail="Try a common asset name or slash-delimited symbol." /> : <div className="grid gap-3 md:grid-cols-2">{cryptoAssets.map(item => <Link key={item.symbol} to="/company/$symbol" params={{ symbol: item.symbol }} className="card flex items-center justify-between"><span><b>{item.symbol}</b><span className="muted ml-3">{item.name}</span></span><ArrowUpRight /></Link>)}</div>}</section></>
}

export function FavoritesPage() {
  const { api } = useAppContext(); const cache = useQueryClient(); const [symbol, setSymbol] = useState('')
  const favorites = useQuery({ queryKey: ['favorites'], queryFn: ({ signal }) => api.get('/v1/favorites?page_size=100', favoritePageSchema, signal), retry: 1 })
  const add = useMutation({ mutationFn: (value: string) => api.mutate('/v1/favorites', 'POST', favoriteRequest({ symbol: value.toUpperCase(), instrumentType: 'equity' }), favoriteSchema, crypto.randomUUID()), onSuccess: () => { setSymbol(''); void cache.invalidateQueries({ queryKey: ['favorites'] }) } })
  const remove = useMutation({ mutationFn: (id: string) => api.mutate(`/v1/favorites/${id}`, 'DELETE', undefined, zUndefined, crypto.randomUUID()), onSuccess: () => void cache.invalidateQueries({ queryKey: ['favorites'] }) })
  return <><PageHeader eyebrow="Research library" title="Favorites">Your saved companies and assets, synchronized to your account.</PageHeader><form onSubmit={event => { event.preventDefault(); if (symbol.trim()) add.mutate(symbol.trim()) }} className="card mb-4 flex gap-3"><label className="sr-only" htmlFor="favorite-symbol">Symbol</label><input id="favorite-symbol" value={symbol} onChange={event => setSymbol(event.target.value)} placeholder="Add a symbol" maxLength={20} className="w-full bg-transparent px-2 py-2" /><button disabled={add.isPending} className="rounded-lg bg-sky-400 px-4 font-semibold text-slate-950">Add</button></form>{(add.isError || remove.isError) && <p role="alert" className="mb-4 text-rose-300">The favorite could not be updated. Try again.</p>}{favorites.isPending ? <LoadingState /> : favorites.isError ? <ErrorState retry={() => favorites.refetch()} /> : favorites.data.items.length === 0 ? <EmptyState title="No favorites yet" detail="Add a symbol to create your research shortlist." /> : <div className="grid gap-3">{favorites.data.items.map(item => <article className="card flex items-center justify-between" key={item.id}><Link to="/company/$symbol" params={{ symbol: item.symbol }}><b>{item.symbol}</b><span className="muted ml-3 text-sm">{item.instrument_type}</span></Link><button onClick={() => remove.mutate(item.id)} className="text-sm text-rose-300">Remove</button></article>)}</div>}</>
}

export function PortfoliosPage() {
  const { api } = useAppContext(); const cache = useQueryClient(); const [name, setName] = useState('')
  const portfolios = useQuery({ queryKey: ['portfolios'], queryFn: ({ signal }) => api.get('/v1/portfolios?page_size=100', portfolioPageSchema, signal), retry: 1 })
  const create = useMutation({ mutationFn: (value: string) => api.mutate('/v1/portfolios', 'POST', portfolioRequest({ name: value, baseCurrency: 'USD' }), portfolioSchema, crypto.randomUUID()), onSuccess: () => { setName(''); void cache.invalidateQueries({ queryKey: ['portfolios'] }) } })
  return <><PageHeader eyebrow="Allocation" title="Portfolios">Create portfolios to understand concentration, exposure, and performance.</PageHeader><form onSubmit={event => { event.preventDefault(); if (name.trim()) create.mutate(name.trim()) }} className="card mb-4 flex gap-3"><label className="sr-only" htmlFor="portfolio-name">Portfolio name</label><input id="portfolio-name" value={name} onChange={event => setName(event.target.value)} placeholder="New portfolio name" maxLength={100} className="w-full bg-transparent px-2 py-2" /><button disabled={create.isPending} className="rounded-lg bg-sky-400 px-4 font-semibold text-slate-950">Create</button></form>{create.isError && <p role="alert" className="mb-4 text-rose-300">The portfolio could not be created.</p>}{portfolios.isPending ? <LoadingState /> : portfolios.isError ? <ErrorState retry={() => portfolios.refetch()} /> : portfolios.data.items.length === 0 ? <EmptyState title="No portfolios yet" detail="Create a portfolio to organize positions and research." /> : <div className="grid gap-3 md:grid-cols-2">{portfolios.data.items.map(item => <article className="card" key={item.id}><h2 className="font-semibold">{item.name}</h2><p className="muted mt-2 text-sm">Base currency · {item.base_currency}</p></article>)}</div>}</>
}

export function ReportsPage() {
  const { api } = useAppContext(); const cache = useQueryClient(); const [symbol, setSymbol] = useState('')
  const reports = useQuery({ queryKey: ['reports'], queryFn: ({ signal }) => api.get('/v1/reports?page_size=100', reportPageSchema, signal), retry: 1, refetchInterval: query => query.state.data?.items.some(item => item.status === 'queued' || item.status === 'generating') ? 2_000 : false })
  const create = useMutation({ mutationFn: (value: string) => api.mutate('/v1/reports', 'POST', reportRequest({ symbol: value.toUpperCase() }), reportSchema, crypto.randomUUID()), onSuccess: () => { setSymbol(''); void cache.invalidateQueries({ queryKey: ['reports'] }) } })
  const cancel = useMutation({ mutationFn: (id: string) => api.mutate(`/v1/reports/${encodeURIComponent(id)}/cancel`, 'POST', undefined, reportSchema, crypto.randomUUID()), onSuccess: updated => cache.setQueryData<ReportPage>(['reports'], current => current ? { ...current, items: current.items.map(item => item.id === updated.id ? updated : item) } : current) })
  return <><PageHeader eyebrow="Long-form research" title="Reports">Generate and revisit evidence-backed company research.</PageHeader><form onSubmit={event => { event.preventDefault(); if (symbol.trim()) create.mutate(symbol.trim()) }} className="card mb-4 flex gap-3"><label className="sr-only" htmlFor="report-symbol">Company symbol</label><input id="report-symbol" value={symbol} onChange={event => setSymbol(event.target.value)} placeholder="Company symbol" maxLength={20} className="w-full bg-transparent px-2 py-2" /><button disabled={create.isPending} className="rounded-lg bg-sky-400 px-4 font-semibold text-slate-950">Generate</button></form>{create.isError && <p role="alert" className="mb-4 text-rose-300">The report request could not be queued.</p>}{cancel.isError && <p role="alert" className="mb-4 text-rose-300">The report cancellation could not be requested.</p>}{reports.isPending ? <LoadingState /> : reports.isError ? <ErrorState retry={() => reports.refetch()} /> : reports.data.items.length === 0 ? <EmptyState title="No reports yet" detail="Generate a report to begin your research archive." /> : <div className="grid gap-3">{reports.data.items.map(item => <article className="card flex items-center justify-between gap-4" key={item.id}><span><b>{item.title}</b><span className="muted ml-3 text-sm">{item.symbol}</span></span><span className="flex items-center gap-3"><span className="rounded-full bg-slate-800 px-3 py-1 text-xs capitalize">{item.status}</span>{(item.status === 'queued' || item.status === 'generating') && <button type="button" disabled={cancel.isPending && cancel.variables === item.id} onClick={() => cancel.mutate(item.id)} className="text-sm text-rose-300 disabled:opacity-60">{cancel.isPending && cancel.variables === item.id ? 'Cancelling…' : 'Cancel'}</button>}</span></article>)}</div>}</>
}

export function SettingsPage() {
  const { api } = useAppContext(); const cache = useQueryClient(); const [draft, setDraft] = useState('')
  const user = useQuery({ queryKey: ['current-user'], queryFn: ({ signal }) => api.get('/v1/me', userSchema, signal), retry: 1 })
  const save = useMutation({ mutationFn: (displayName: string) => api.mutate('/v1/me', 'PATCH', userUpdateRequest({ displayName }), userSchema, crypto.randomUUID()), onSuccess: data => { cache.setQueryData(['current-user'], data); setDraft('') } })
  return <><PageHeader eyebrow="Account" title="Settings">Manage your profile and account preferences.</PageHeader>{user.isPending ? <LoadingState /> : user.isError ? <ErrorState retry={() => user.refetch()} /> : <form onSubmit={event => { event.preventDefault(); save.mutate(draft.trim() || user.data.display_name) }} className="card max-w-xl space-y-4"><label className="block text-sm">Email<input disabled value={user.data.email} className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-900 px-3 py-2.5 disabled:opacity-60" /></label><label className="block text-sm">Display name<input value={draft || user.data.display_name} onChange={event => setDraft(event.target.value)} maxLength={100} className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-900 px-3 py-2.5" /></label>{save.isError && <p role="alert" className="text-rose-300">Your settings could not be saved.</p>}<button disabled={save.isPending} className="rounded-lg bg-sky-400 px-4 py-2 font-semibold text-slate-950">Save changes</button></form>}</>
}

function Change({ value }: { value: number }) { return <span className={`ml-2 text-sm ${value >= 0 ? 'text-emerald-400' : 'text-rose-400'}`}>{value >= 0 ? '+' : ''}{value.toFixed(2)}%</span> }
function money(value: number) { return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(value) }
const zUndefined = z.undefined()
