imageDigest: sha256:8fcf2b1d4ce6f0d13712e7a3cd8a08dbfa5373d1755a8321779530ec9048fc6d
replicas: 1
minReplicas: 1
maxReplicas: 2
resources:
  requests: { cpu: 250m, memory: 512Mi }
  limits: { cpu: "1", memory: 1Gi }
