export interface GeminiMessage {
	role: "user" | "model" | "system";
	parts: { text: string }[];
}

interface GeminiStreamChunk {
	candidates?: Array<{
		content?: {
			parts?: Array<{ text?: string }>;
		};
		finishReason?: string;
	}>;
}

const BASE_URL = "https://generativelanguage.googleapis.com/v1beta";
const MODEL = "gemini-2.5-flash";
const GENERATION_CONFIG = {
	temperature: 0.1,
	topK: 1,
	topP: 0.8,
	maxOutputTokens: 2048,
};

export function createGeminiRequestBody(messages: GeminiMessage[]) {
	const systemParts = messages
		.filter((message) => message.role === "system")
		.flatMap((message) => message.parts);
	const contents = messages
		.filter((message) => message.role !== "system")
		.map((message) => ({ role: message.role, parts: message.parts }));

	return {
		contents,
		...(systemParts.length > 0 ? { systemInstruction: { parts: systemParts } } : {}),
		generationConfig: GENERATION_CONFIG,
	};
}

export interface ParsedSseBuffer {
	texts: string[];
	remainder: string;
}

export class GeminiApiError extends Error {
	constructor(
		public readonly status: number,
		statusText: string,
	) {
		super(`Gemini request failed with ${status} ${statusText}`);
		this.name = "GeminiApiError";
	}
}

export class GeminiClient {
	private readonly apiKey: string;

	constructor(apiKey: string) {
		this.apiKey = apiKey;
	}

	async generateStreamingContent(messages: GeminiMessage[]): Promise<ReadableStream<Uint8Array>> {
		const url = `${BASE_URL}/models/${MODEL}:streamGenerateContent?alt=sse`;

		const response = await fetch(url, {
			method: "POST",
			headers: {
				"Content-Type": "application/json",
				"x-goog-api-key": this.apiKey,
			},
			body: JSON.stringify({
				...createGeminiRequestBody(messages),
				safetySettings: [
					{
						category: "HARM_CATEGORY_HARASSMENT",
						threshold: "BLOCK_MEDIUM_AND_ABOVE",
					},
					{
						category: "HARM_CATEGORY_HATE_SPEECH",
						threshold: "BLOCK_MEDIUM_AND_ABOVE",
					},
					{
						category: "HARM_CATEGORY_SEXUALLY_EXPLICIT",
						threshold: "BLOCK_MEDIUM_AND_ABOVE",
					},
					{
						category: "HARM_CATEGORY_DANGEROUS_CONTENT",
						threshold: "BLOCK_MEDIUM_AND_ABOVE",
					},
				],
			}),
		});

		if (!response.ok) {
			throw new GeminiApiError(response.status, response.statusText);
		}

		if (!response.body) {
			throw new Error("Gemini returned an empty response body");
		}

		return response.body;
	}

	async generateContent(messages: GeminiMessage[]): Promise<string> {
		const url = `${BASE_URL}/models/${MODEL}:generateContent`;

		const response = await fetch(url, {
			method: "POST",
			headers: {
				"Content-Type": "application/json",
				"x-goog-api-key": this.apiKey,
			},
			body: JSON.stringify(createGeminiRequestBody(messages)),
		});

		if (!response.ok) {
			throw new GeminiApiError(response.status, response.statusText);
		}

		const data = (await response.json()) as GeminiStreamChunk;
		const text = data.candidates?.[0]?.content?.parts?.[0]?.text;
		if (text) {
			return text;
		}

		throw new Error("No content generated by Gemini");
	}

	static parseStreamChunk(chunk: string): string | null {
		try {
			const data: GeminiStreamChunk = JSON.parse(chunk);
			return data.candidates?.[0]?.content?.parts?.[0]?.text || null;
		} catch {
			return null;
		}
	}

	static parseSseBuffer(buffer: string, flush = false): ParsedSseBuffer {
		const normalized = buffer.replace(/\r\n/g, "\n");
		const events = normalized.split("\n\n");
		const remainder = flush ? "" : (events.pop() ?? "");
		const texts: string[] = [];

		for (const event of events) {
			const payload = event
				.split("\n")
				.filter((line) => line.startsWith("data:"))
				.map((line) => line.slice(5).trimStart())
				.join("\n");

			if (!payload || payload === "[DONE]") {
				continue;
			}

			const text = GeminiClient.parseStreamChunk(payload);
			if (text) {
				texts.push(text);
			}
		}

		return { texts, remainder };
	}
}
