environment: production
clusterName: indus-production
vpcId: vpc-replace-production
awsRegion: us-east-1
roles:
  loadBalancer: arn:aws:iam::444444444444:role/indus-production-load-balancer
legacyNext:
  enabled: true
platform:
  enabled: false
