environment: staging
clusterName: indus-staging
vpcId: vpc-replace-staging
awsRegion: us-east-1
roles:
  loadBalancer: arn:aws:iam::333333333333:role/indus-staging-load-balancer
legacyNext:
  enabled: true
platform:
  enabled: false
